# Generated by Django 2.2.4 on 2020-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0004_auto_20201215_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_shows',
            name='release_date',
            field=models.DateField(max_length=45, null=True),
        ),
    ]
