# Generated by Django 2.2.4 on 2021-04-01 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beat_app', '0004_remove_beat_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='favorited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='beat_app.User'),
        ),
    ]
