# Generated by Django 2.2.4 on 2021-04-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_app', '0006_beat_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='beat_app.User'),
        ),
    ]
