# Generated by Django 2.2.4 on 2021-04-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_app', '0008_auto_20210403_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_beats',
            field=models.ManyToManyField(related_name='user_liked_beats', to='beat_app.Beat'),
        ),
    ]
