# Generated by Django 2.2.4 on 2020-12-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20201218_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
